- lisp目录包含emacs配置文件。

- project目录包含python练习文件。


* 2012-11-15 
 添加/lisps/python目录, 保存备份rope、ropemacs、ropemode、pymacs。添加init_python.el对python设置。


* 2013-3-14
用jedi替换rope ropemacs ropemode pymacs , 不用python-mode.


* 2013-4-23
添加cscope。 在unbuntu下直接sudo apt-get install cscope 即可。
在mac下安装，看mac.org

* 2013-4-28
今天发现一个问题，就是在安装了auto-complete-clang之后，由于把auto-complete和auto-complete-clang的配置代码整合在一起，写在了init_initjedi.el中。导致jede:complete的快捷键定制失效。
虽然最后也没有弄清楚具体是为什么会这样。但是，可以把关于auto-complete和auto-complete-clang的配置整合到init_auto-complete-clang.el文件中，并把init_initjedi.el文件放到.emacs最后。



* 2013-5-12
今天记录一下一台全新的系统，如何安装配置emacs

** 安装git

   - 在ubuntu下只需要sudo apt-get install git

   - 在mac下好像需要去git官网，按照教程安装

** 安装emacs

   - 在ubuntu下可以添加ppa，来安装最新版本的emacs

	https://launchpad.net/~cassou/+archive/emacs

   - 在mac下可以安装emacsformac版本。

       或者自己编译，不过直接安装挺好的。

** 使用git下载emacs的配置文件

   git clone https://github.com/weikent/emacs 到~/ 目录

** 安装cscope

   - 在ubuntu下

       sudo apt-get install cscope

   - 在mac下

       看emacs.org

** 安装clang

   - 在ubuntu下

       sudo apt-get install clang

   - 在mac下
   
       mac里面好像自带clang
	   
** 安装"virtualenv" for jedi

   - 在ubuntu下
   
       sudo apt-get install python-virtualenv
	   
   - 在mac下
   
       看init_initjedi.el
	   
** 启动 emacs

   - 创建.emacs文件
   
   - M-x el-get-install RET jedi
   
   - M-x el-get-install RET auto-complete
   
   - M-x el-get install RET auto-complete-clang
   
   - M-x el-get install RET pos-tip
   
   - M-x el-get install RET fuzzy
   
   - M-x el-get isntall RET popup
   
   - 退出emacs 重新启动 即可
   
** 可以在系统启动时，添加启动项

   emacsclient -c -a "" 来启动emacs daemon
