#+Title English 


* at和on和in的用法?

** 地方介系詞 at 、on 、in 之比較
[at] 強調場所中的「點」，[on] 強調場所中的「面」及「線」，[in]強調場所中的「立體空間」。


 1) [at] 強調場所/位置中的「點」: at 通常用來表示可視為"一點"的場所，即使地方大，只要說話人將其視為"一點"，則可用at。
 2) [on] 強調場所/位置中的「面」及「線」: 指在....(面)上，在.....(路線)上
 3) [in]強調場所/位置中的「立體空間」: in通常用來表示在某空間之內，不論地點大小，只要說話者著眼於"空間 (在.....裡)"，即用in。

*** 比較1: 
on a river (在河面上) 
in a river (在河裡)


*** 比較2:

1 in the corner of a room 

(在房間的角落裡—將角落視為一個「長寬高」皆具的"立體空間")

2 at the corner of a street 

(在街的角落上—將角落視為"一點")

3 on the corner of a street 

(在街的角落上—強調在街角的"街面"上)



----------------例句比較-------------



【比較一】at the station 及 in the station

(1) We met him at the station. 

車站雖是立體空間，但由於此句強調"碰面的地點"(此時的車站如同地圖上的一點)，因此介系詞用表示「點」的 at。

(2) People in the station are tired, weary and exhausted.

說明在車站內的人們很疲累，強調"場所內部的空間"，因此介系詞用表示「立體空間」的 in。



【比較二】 on the street 及 in the street

(1) I met her on the street.

街雖是立體空間，但此句強調在某"街面上"(有腳踏於地面的感覺)遇見她，因此用表示「面」的 on。

(2) I met her in the street.

說明在街上遇見她，強調被眼前這個街上的立體空間所環繞(有置身於街上這個立體空間的感覺)，因此用表示「立體空間」的 in。



【比較三】on one's way 及in one's way

(1) He is on his way home.

回家的道路，是一條路線，強調「線狀」空間，因此用表示「線」的 on。

(2) Excuse me! You are in my way!

對方擋住路，是擋住一個「長寬高」皆具的"空間"，對方要讓出一個「立體空間」才能讓自已順利通過。因此用表示「立體空間」的 in。



----------補充說明---------------



一般國內外文法書及傳統文法教學常將此三介系詞的使用規則以所指的"地點大小"來區分(at+小型地點，on+中型地點，in+大型地點)。但地點的大小常因個人觀感不同而有所差異，因此此種分類方法常會對學習者造成困擾。



舉例:



(1)factory比car大，但我們講 at a factory (在工廠)、in a car (在車子裡)，是因為當我們談到「在工廠時」，所強調的是在工廠這個「地點」，當我們談到「在車子裡」時，所強調的是在車內的「立體空間」裡。



(可看出介系詞的使用並非以地點的大小型來區分)

(2)當我們說"街道、河川"時，通常用介系詞「on」。

如on Tenth Street(第十街)--因第十街是「路線」故用強調「線」的on。又如on the Yellow River(在黃河)--因在河"面"上，故用強調「面」的「on 」。

(非因街道、河川為中型地點)

因此以書寫者所要強調的為地點/位置的「點、線、面、立體空間」來區別「at、on、in」的使用，是較簡易且正確的方法。

** 時間介系詞 at、on、in 的比較

以[at ] 表示「點」;以 [on]標示出「(特定)日期」或和「日期」連用的某一時間段;以[in]表示除日以外的「某一時段」。



(一) 以[at ] 表示「點」。(at 在此有「點」的感覺)



(1) [at ]表示一天中的某時刻，不用冠詞，如at 5 :20 A.M.(在凌晨5點20分)，at 11 o'clock (在11點整)，at dawn(在黎明)，at sunrise(日出時)，at noon(在正午)，at night(在晚上)，at sunset(日落時)。



(2) [at ]表示一瞬間或短暫的時間，如at that moment(在那一瞬間)，at present(目前)，at that time (那時)，at breakfast (早餐時)。



(3) [at ]表示某特定節日期間(public holiday periods)，如at Christmas(或寫成 at Christmas time )，at Easter (在復活節)。



(4) [at ]表示年齡「點」，如at the age of ten (在十歲時)，at 16(在十六歲時)。



(二) 以 [on]標示出「(特定)日期」或和日期連用的某一時間段



(1)以[on]表示某日或某特定日期，如on Monday (在星期一)， on Christmas Day (在聖誕節，指在當天)，on Independence Day (獨立紀念日)。



(2)以[on] 表示和某日連用的某一時段，如on Friday afternoon(在星期五下午)， on the morning of August the eighth(在八月八日早晨)。



(三) 以[in]表示除日以外的「某一時段」，有「線」的感覺。



(1)[in] 表示年、月、季節、世紀、時代，如 in 1997(在1997年)， in May(在五月)，in winter(在冬季)， in the 20th century(在二十世紀)，in the eighties(在八十年代)，in modern times (在現代)。



(2)與「定冠詞」連用表示一天中某個「時間段」，如in the night(在晚上)， in the morning (afternoon, evening)在早上 (下午，晚上)。



(3)[in ]表示「年齡段、時間段或在某段經歷」中，如：in one's youth(在某人青年時代) , in those days(在那些日子裡), in one’s school days.(在某人的學生時代)。



比較1:

on Christmas Day ----在聖誕節當天 (on標示特定日期)。

at Christmas (time) ---在聖誕節期間 (at標示public holiday periods)。



比較2:

in the morning --- 在早上，著眼於從dawn到noon的這個「時間段」。

on Monday morning ---在星期一早上，著眼於「特定日期」中的某時段。



比較3:

at night ---在晚上，夜晚，將night視為一個「時間點」。

in the night ---在夜間，強調(從sunset 到sunrise)的這個「時段」。

in the evening ---強調 (從sunset到bedtime)的這個「時段」。



註:時間介系詞的比較，部分內容參考自「溫世仁先生的動畫文法」。




* what about 與 how about 有何差異性 
- 在表達提出某種建議的意思時, 即"~怎麼樣;~好嗎?"時, what about 和 how about 是可以互換的,因為意思相同.例如:What should we go now?  How/What about going  to the movies? (我們現在要去哪呢?去看電影怎麼樣呢?)     比方說:How about taking a walk? (散個步好嗎?)
- 若是詢問意見或打聽消息時, 就只能使用 what about了.例如:Andy, we are going to the harbor by ship. What about you? (Andy,我們政要搭船到海港去.你呢?)
- 若是提供多項事物讓人選擇的話,則使用 how about.比方說:Mary, I suggest to go to McDonald or KFC to have lunch. How about you and your sister?* test2

* have been 是什么时态
- have/has been +名词，现在完成时态的主动语态
- have/has been +动词的过去分词（done)，现在完成时态的被动语态
- have/has been +动词的现在分词(doing)，现在完成进行时态的主动语态
- had been +名词，过去完成时态的主动语态
- had been +动词的过去分词（done)，过去完成时态的被动语态
- had been +动词的现在分词(doing)，过去完成进行时态的主动语态
* each和every的区别
** each 强调个体，是形容词(adj)和代词(PRON).形容词时，起修饰限定作用，代词可以单独使用。each指2个或2个以上中的每一个。
- each boy
- each of the boys
- each of my hands
- each of my parents
** every 强调整体，只能做adj
every 指三个或三个以上中的每一个。
- every students (不能写为every of the student) 
- every one of my fingers. 
