#+Title English 


* at和on和in的用法?

** 地方介系~ at 、on 、in 之比^
[at] {鏊中的「c」，[on] {鏊中的「面」及「」，[in]{鏊中的「立w空g」。


 1) [at] {鏊/位置中的「c」: at 通常用肀硎究梢"一c"的鏊，即使地方大，只要f人⑵湟"一c"，t可用at。
 2) [on] {鏊/位置中的「面」及「」: 指在....(面)上，在.....(路)上
 3) [in]{鏊/位置中的「立w空g」: in通常用肀硎驹谀晨臻g之龋不地c大小，只要f者著眼於"空g (在.....e)"，即用in。

*** 比^1: 
on a river (在河面上) 
in a river (在河e)


*** 比^2:

1 in the corner of a room 

(在房g的角落e―⒔锹湟橐「L高」皆具的"立w空g")

2 at the corner of a street 

(在街的角落上―⒔锹湟"一c")

3 on the corner of a street 

(在街的角落上―{在街角的"街面"上)



----------------例句比^-------------



【比^一】at the station 及 in the station

(1) We met him at the station. 

站m是立w空g，但由於此句{"碰面的地c"(此r的站如同地D上的一c)，因此介系~用表示「c」的 at。

(2) People in the station are tired, weary and exhausted.

f明在站鹊娜很疲累，{"鏊炔康目臻g"，因此介系~用表示「立w空g」的 in。



【比^二】 on the street 及 in the street

(1) I met her on the street.

街m是立w空g，但此句{在某"街面上"(有_踏於地面的感X)遇她，因此用表示「面」的 on。

(2) I met her in the street.

f明在街上遇她，{被眼前@街上的立w空g所h@(有置身於街上@立w空g的感X)，因此用表示「立w空g」的 in。



【比^三】on one's way 及in one's way

(1) He is on his way home.

回家的道路，是一l路，{「睢箍臻g，因此用表示「」的 on。

(2) Excuse me! You are in my way!

Ψ踝÷罚是踝∫「L高」皆具的"空g"，Ψ揭出一「立w空g」才能自已利通^。因此用表示「立w空g」的 in。



----------a充f明---------------



一般韧馕姆及鹘y文法教W常⒋巳介系~的使用t以所指的"地c大小"^分(at+小型地c，on+中型地c，in+大型地c)。但地c的大小常因人^感不同而有所差，因此此N分方法常W者造成困_。



e例:



(1)factory比car大，但我v at a factory (在工S)、in a car (在子e)，是因楫我到「在工Sr」，所{的是在工S@「地c」，我到「在子e」r，所{的是在鹊摹噶Ⅲw空g」e。



(可看出介系~的使用K非以地c的大小型^分)

(2)我f"街道、河川"r，通常用介系~「on」。

如on Tenth Street(第十街)--因第十街是「路」故用{「」的on。又如on the Yellow River(在S河)--因在河"面"上，故用{「面」的「on 」。

(非因街道、河川橹行偷攸c)

因此以者所要{的榈攸c/位置的「c、、面、立w空g」^e「at、on、in」的使用，是^易且正_的方法。

** rg介系~ at、on、in 的比^

以[at ] 表示「c」;以 [on]耸境觥(特定)日期」或和「日期」B用的某一rg段;以[in]表示除日以外的「某一r段」。



(一) 以[at ] 表示「c」。(at 在此有「c」的感X)



(1) [at ]表示一天中的某r刻，不用冠~，如at 5 :20 A.M.(在凌晨5c20分)，at 11 o'clock (在11c整)，at dawn(在黎明)，at sunrise(日出r)，at noon(在正午)，at night(在晚上)，at sunset(日落r)。



(2) [at ]表示一瞬g或短旱rg，如at that moment(在那一瞬g)，at present(目前)，at that time (那r)，at breakfast (早餐r)。



(3) [at ]表示某特定日期g(public holiday periods)，如at Christmas(或成 at Christmas time )，at Easter (在突罟)。



(4) [at ]表示年g「c」，如at the age of ten (在十qr)，at 16(在十六qr)。



(二) 以 [on]耸境觥(特定)日期」或和日期B用的某一rg段



(1)以[on]表示某日或某特定日期，如on Monday (在星期一)， on Christmas Day (在}Q，指在天)，on Independence Day (立o念日)。



(2)以[on] 表示和某日B用的某一r段，如on Friday afternoon(在星期五下午)， on the morning of August the eighth(在八月八日早晨)。



(三) 以[in]表示除日以外的「某一r段」，有「」的感X。



(1)[in] 表示年、月、季、世o、r代，如 in 1997(在1997年)， in May(在五月)，in winter(在冬季)， in the 20th century(在二十世o)，in the eighties(在八十年代)，in modern times (在F代)。



(2)c「定冠~」B用表示一天中某「rg段」，如in the night(在晚上)， in the morning (afternoon, evening)在早上 (下午，晚上)。



(3)[in ]表示「年g段、rg段或在某段v」中，如：in one's youth(在某人青年r代) , in those days(在那些日子e), in one’s school days.(在某人的W生r代)。



比^1:

on Christmas Day ----在}Q天 (on耸咎囟ㄈ掌)。

at Christmas (time) ---在}Q期g (at耸public holiday periods)。



比^2:

in the morning --- 在早上，著眼於dawn到noon的@「rg段」。

on Monday morning ---在星期一早上，著眼於「特定日期」中的某r段。



比^3:

at night ---在晚上，夜晚，night橐「rgc」。

in the night ---在夜g，{(sunset 到sunrise)的@「r段」。

in the evening ---{ (sunset到bedtime)的@「r段」。



]:rg介系~的比^，部分热⒖甲浴厥廊氏壬的赢文法」。




* what about c how about 有何差性 
- 在表_提出某N建h的意思r, 即"~怎N;~好?"r, what about 和 how about 是可以互Q的,因橐馑枷嗤.例如:What should we go now?  How/What about going  to the movies? (我F在要去哪呢?去看影怎N幽?)     比方f:How about taking a walk? (散步好?)
- 若是意或打消息r, 就只能使用 what about了.例如:Andy, we are going to the harbor by ship. What about you? (Andy,我政要搭船到海港去.你呢?)
- 若是提供多事物人x竦脑,t使用 how about.比方f:Mary, I suggest to go to McDonald or KFC to have lunch. How about you and your sister?* test2

* have been 是什么时态
- have/has been +名词，现在完成时态的主动语态
- have/has been +动词的过去分词（done)，现在完成时态的被动语态
- have/has been +动词的现在分词(doing)，现在完成进行时态的主动语态
- had been +名词，过去完成时态的主动语态
- had been +动词的过去分词（done)，过去完成时态的被动语态
- had been +动词的现在分词(doing)，过去完成进行时态的主动语态
* each和every的区别
** each 强调个体，是形容词(adj)和代词(PRON).形容词时，起修饰限定作用，代词可以单独使用。each指2个或2个以上中的每一个。
- each boy
- each of the boys
- each of my hands
- each of my parents
** every 强调整体，只能做adj
every 指三个或三个以上中的每一个。
- every students (不能写为every of the student) 
- every one of my fingers.
