#+TITLE  XCODE

* 关于xib
  用xib文件添加视图的时候，在4.2版本的xcode中，程序会报错。需要把view按住control键拖到文件里面。生成一下自动代码，并删除自动代码之后就正常了。
** Xcode4.2 
   Xcode4.2 中清理xib缓存
   1. option + product menu    ->  Clean Build Folder
   2. iOS Simulator -> Reset Content and settings


* 获取IOS设备的类型和系统版本
#+begin_src objc
//  DeviceHelper.m   
//  DeviceUtil   
//   
//  Created by LUOYL on 12-4-9.   
//  Copyright (c) 2012年 http://luoyl.info. All rights reserved.   
//   
  
#import "DeviceHelper.h"   
#import "sys/utsname.h"   
  
@implementation DeviceHelper   
  
/*  
 *功能：获取设备类型  
 *  
 *  AppleTV2,1    AppleTV(2G)  
 *  i386          simulator  
 *  
 *  iPod1,1       iPodTouch(1G)  
 *  iPod2,1       iPodTouch(2G)  
 *  iPod3,1       iPodTouch(3G)  
 *  iPod4,1       iPodTouch(4G)  
 *  
 *  iPhone1,1     iPhone  
 *  iPhone1,2     iPhone 3G  
 *  iPhone2,1     iPhone 3GS  
 *  
 *  iPhone3,1     iPhone 4  
 *  iPhone3,3     iPhone4 CDMA版(iPhone4(vz))  
 
 *  iPhone4,1     iPhone 4S  
 *  
 *  iPad1,1       iPad  
 *  iPad2,1       iPad2 Wifi版  
 *  iPad2,2       iPad2 GSM3G版  
 *  iPad2,3       iPad2 CDMA3G版  
 *  @return null  
 */  
+ (NSString *)getDeviceVersion   
{   
    struct utsname systemInfo;   
    uname(&systemInfo);   
    //get the device model and the system version   
    NSString *machine =[NSString stringWithCString:systemInfo.machine encoding:NSUTF8StringEncoding];    
    return machine;   
}   
  
/** 获取IOS系统的版本号 */  
+ (NSString*)getOSVersion   
{   
    return [[UIDevice currentDevice]systemVersion];   
}   
  
/** 判断当前设备是否ipad */  
+ (BOOL)isIpad   
{   
    return [UIDevice currentDevice].userInterfaceIdiom == UIUserInterfaceIdiomPad;   
}   
  
/** 判断当前设备是否iphone */  
  
+ (BOOL)isIphone   
{   
    return [UIDevice currentDevice].userInterfaceIdiom == UIUserInterfaceIdiomPhone;   
  
}   
  
/** 判断当前系统是否有摄像头 */  
+ (BOOL)hasCamera   
{   
    return [UIImagePickerController isSourceTypeAvailable:UIImagePickerControllerSourceTypeCamera];   
}   
  
@end   

#+end_src 

* iOS学习笔记――字符串编码转换

我们知道，使用NSURLConnection的代理方法下载网页，存到一个NSData中，

#+begin_src objc
NSMutableData *pageData;
[pageData appendData:data];
#+end_src

如果网页编码是UTF-8的，可以这么转换为字符串：

#+begin_src objc
NSString *pageSource = [[NSString alloc] initWithData:pageData encoding:NSUTF8StringEncoding];
#+end_src 

如果网页是gbk（或者gb2312），用UTF8转换的话，pageSource返回nil。这时需要使用gbk编码做转换，但是NSStringEncoding不含gbk，怎么办？用另一个方法处理一下：

#+begin_src objc
NSStringEncoding gbkEncoding = CFStringConvertEncodingToNSStringEncoding(kCFStringEncodingGB_18030_2000);
NSString *pageSource = [[NSString alloc] initWithData:pageData encoding:gbkEncoding];
#+end_src

为什么可以这么处理？在NSString.h（按住command，双击NSStringEncoding即能查看），对NSStringEncoding的定义中，注释这么写着：

Note that in addition to the values explicitly listed below, NSStringEncoding supports encodings provided by CFString.

See CFStringEncodingExt.h for a list of these encodings.

See CFString.h for functions which convert between NSStringEncoding and CFStringEncoding.
